# Generated by Django 5.0.2 on 2024-03-28 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время')),
                ('action', models.CharField(max_length=300, verbose_name='действие')),
                ('is_nice', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('period', models.PositiveIntegerField(default=1, verbose_name='периодичность')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='вознаграждение')),
                ('action_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='время выполнения привычки')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('good_habit', models.BooleanField(default=False, verbose_name='полезная привычка')),
                ('associated_hab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
