# Generated by Django 5.0.2 on 2024-04-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('period',), 'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
    ]
